name: Test
on:
  pull_request:
jobs:
  get_scala_versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # https://github.com/actions/checkout
      - uses: exoego/cross-scala-versions@master
        id: run
    outputs:
      scala_versions: ${{ steps.run.outputs.scala_versions }}

  build:
    needs: get_scala_versions
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala: ${{ fromJson(needs.get_scala_versions.outputs.scala_versions) }}
    steps:
      - run: echo v${{ matrix.scala }}
